// <auto-generated />
namespace EuroApi.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202231713279_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9N1XR2virG0/Cg9LouMsHidl+fvidLOQ6D0ke2MujsltNrrN9ernLv87KM3eRa0oDa/V34dfEAfvayrVV6316/yc33vbPZRejd87273Rfua9w66pt+W7b29j9IX67LMJiV9cJ6VTf5Ruvr00eu2qvPP82VeZ20+e5m1bV4v8W7OqCsJHq0+vR0VHt7d2QMV7mbLZdVmLc1uD/EOmvjXIPq6rYlRPkqfFe/y2fN8edHOLbJfZO/MJ/TrR+lXy4L4il5q63XuD07+9jt9fNdNRH96iFvarCAKKELKEfg4f9d2ZkteeZ233oQS1zj4wjpjnugoErY7x5V3hS0N+94d4N/HX2SrFdHH42f9JH0tzHyy/fr9mXYhMO5OmwjvWmxtT8Qw2UXe+Za6JkyfFXXTPs3abJJhxk5mi16z2xHXdObTuCskjuSmNX4PplCFetyXOoag7z2j8SyI3XloOjDCISas+uLraVZmdUTcTqpyvVgOieymt0UK/Pflkz6Ex3c7eHcJ4zG7tuwoji6ZNzFpt4nt3TJrhykfK4PcrHl7HCNNPkqJNJfFDNzy+rpp88UYDcavf1F5UhY0Xtfgi2xZnOdN+6Z6m8OKEEN/fQVuVVfTzMr/N2rxAkO/UV/3lPztte/yMqun86zeWmTv7nyTGrWvG25WqoM6Vbjks49mk4oQFwRVC39Nddvn2Md3fY/i8dO8KS4cCPgXy3wK4+aAmjZny/PK0JhG5GNkmnSm4Iu8zWZEmOO6Lc6zaUtfT/OmYUP4k1m5hj5bTPLZ2fLLdbtat8dNky8m5bU/3sd3N/fPNiXE+fGXK/zliejXHwKhWdAQ8i+XT9ZFObN4P+uz4BAI8IjyNWFFjgCBu7i2kF5Uy1sCUvI9zVf5ElLxJl+sSgLWfLl8nV3mw7jdTMOQYo+fFtlFTYznUVA+UUxeZ9Sz1wV14L/h+qM/iV3JnT36fwIAAP//X9gr3UMLAAA="; }
        }
    }
}
